# Generated by Django 2.0 on 2017-12-25 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=None, max_length=20)),
                ('phone_number', models.CharField(default=None, max_length=13, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
        ),
    ]
